services:
  ord-indexer:
    image: reallyshadydev/wonky-ord-dogecoinEV
    env_file:
      - .env
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - STARTING_SATS_PATH=/starting_sats.json
      - SUBSIDIES_PATH=/subsidies.json
      - FIRST_INSCRIPTION_HEIGHT=0
      - FIRST_DUNE_HEIGHT=0
    tty: false
    restart: "always"
    # for the indexer to be able to connect to the local dogecoin node we use the host network
    network_mode: "host"
    #    ports:
    #      - ${ORD_HTTP_PORT:-8080}:80
    entrypoint: [
      "ord",
      "--rpc-url=${RPC_URL}",
      "--data-dir=/root/.data",
      "--nr-parallel-requests=250",
      "--first-inscription-height=${FIRST_INSCRIPTION_HEIGHT}",
      "--first-dune-height=${FIRST_DUNE_HEIGHT}",
      "--index-dunes",
      "--index-transactions",
      "--index-drc20",
      "server"
    ]
    volumes:
      - ${DOG_MOUNT_DIR_INDEXER:-/mnt/ord-node}/indexer-data-main:/root/.data:delegated
      # If your dogecoin node is running in a container, you can mount the dogecoin data directory to the indexer container
      # - dog-data:/root/.dogecoin
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    privileged: true
